---
rh_token_refresh_api_offline_token: "{{ offline_token | default(lookup('env', 'REDHAT_OFFLINE_TOKEN')) }}"
rh_token_refresh_token_cache_file: "/tmp/redhat_refresh_token.json"
rh_token_refresh_token_max_age_seconds: 900 # 15 minutes * 60 seconds

# Character used for separating log blocks
separator_char: "*"

# Define a standard length for the calculation (must be an integer)
default_message_padding: 4

# --- Control Variable Default ---
# This default is necessary in case 'target_environment' is not set via -e or inventory
target_environment_local: "prod"

# --- Lookups (These variables are computed at runtime based on the final, merged rh_env_config) ---
# NOTE: The 'rh_env_config' dictionary must be available in the play's scope.
rh_api_base_url: "{{ rh_env_config[target_environment].rh_token_refresh_api_base_url }}"
rh_base_url: "{{ rh_env_config[target_environment].rh_base_url }}"
rh_token_url: "{{ rh_env_config[target_environment].rh_token_refresh_api_token_url }}"
rh_use_proxy: "{{ rh_env_config[target_environment].rh_use_proxy | default(false) }}"
rh_http_proxy: "{{ rh_env_config[target_environment].rh_http_proxy }}"
# --- End of defaults/main.yml ---
...
