# --- Main Task File for  ---
---
- name: Main | Print on screen role execution status
  ansible.builtin.debug:
    msg:
      - "{{ separator_char * (message_text | length + default_message_padding) | int }}"
      - " {{ message_text }} "
      - "{{ separator_char * (message_text | length + default_message_padding) | int }}"
  vars:
    message_text: "Starting Red Hat Support Case Creation Process Role Execution"
  run_once: true

- name: Main | Include Pre-Validation Tasks
  ansible.builtin.include_tasks: 1-pre_validation.yml

- name: Main | Include Case Creation Tasks
  ansible.builtin.include_tasks: 2-create_case.yml

- name: Main | Include Post-Creation Update Tasks
  ansible.builtin.include_tasks: 3-post_validation.yml

- name: Main | Include Post-Creation Comment Tasks
  ansible.builtin.include_tasks: 4-post_comment.yml

- name: Main | Print on screen role completion status
  ansible.builtin.debug:
    msg:
      - "{{ separator_char * (message_text | length + default_message_padding) | int }}"
      - " {{ message_text }} "
      - "{{ separator_char * (message_text | length + default_message_padding) | int }}"
  vars:
    message_text: "Completed Red Hat Support Case Creation Process Role Execution"
  run_once: true

- name: Main | Extract Case ID from URL and set as global fact
  ansible.builtin.set_fact:
    new_case_id: "{{ case_creation_result.json.location[0].split('/')[-1] }}"
...
