---
rh_token_refresh_base_url: "https://access.redhat.com"
rh_token_refresh_api_base_url: "https://api.access.redhat.com"
rh_token_refresh_api_token_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
...
