---
galaxy_info:
  author: Diego Felipe Mateus - dfmateus@redhat.com
  description: Creates a new support case via the Red Hat Support API.
  company: Red Hat
  issue_tracker_url: https://github.com/redhat-cop/infra.support_assist/issues
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  galaxy_tags: []
dependencies: []
...
