---
- name: Clear Token | Delete this token
  ansible.platform.token:
    aap_hostname: "{{ aap_api_token_aap_hostname }}"
    aap_token: "{{ aap_api_token_aap_token }}"
    existing_token: "{{ aap_api_token_aap_token }}"
    state: absent
    aap_validate_certs: "{{ aap_api_token_aap_validate_certs }}"
  no_log: "{{ aap_api_token_no_log | default(true) | bool }}"
  when: __clear_token | default(false)
  tags:
    - always
...
