---
rh_case_update_timeout: "{{ upload_timeout | default(1800) }}"  # Timeout for file uploads in seconds (default: 1800 seconds = 30 minutes)

# Character used for separating log blocks
separator_char: "*"

# Define a standard length for the calculation (must be an integer)
default_message_padding: 4

# --- Control Variable Default ---
# This default is necessary in case 'target_environment' is not set via -e or inventory
target_environment_local: "prod"

# --- Lookups (These variables are computed at runtime based on the final, merged rh_env_config) ---
# NOTE: The 'rh_env_config' dictionary must be available in the play's scope.
rh_api_base_url: "{{ rh_env_config[target_environment].rh_token_refresh_api_base_url }}"
rh_base_url: "{{ rh_env_config[target_environment].rh_base_url }}"
rh_token_url: "{{ rh_env_config[target_environment].rh_token_refresh_api_token_url }}"
rh_use_proxy: "{{ rh_env_config[target_environment].rh_use_proxy | default(false) }}"
rh_http_proxy: "{{ rh_env_config[target_environment].rh_http_proxy }}"

final_update_banner: |
    *******************************************************************************
    SUMMARY STATUS: Red Hat Support Case {{ case_id }} Created and Updated Successfully.
    *******************************************************************************
    [ I. CASE IDENTIFIERS ]
    > Account Name:   => {{ account_name }}
    > Account Ref     => {{ accountNumberRef }}
    > Case ID         => {{ case_id }}
    > Case URL        => {{ rh_base_url }}/support/cases/#/case/{{ case_id }}
    [ II. CASE DETAILS ]
    > Summary         => {{ case_summary | trim }}
    [ III. PROBLEM DETAILS ]
    > Product         => {{ case_product }}
    > Version         => {{ case_product_version }}
    > Severity        => {{ case_severity }}
    > Issue Type      => {{ case_type }}
    [ IV. DESCRIPTION ]
    => {{ case_description | default(case_summary) }}
    ---------------------------------------------------------------------------------
    ACTION REQUIRED: Review the case via the URL above for full file upload details.
    ---------------------------------------------------------------------------------
...
# --- End of defaults/main.yml ---