---
rh_case_update_timeout: "{{ upload_timeout | default(1800) }}"  # Timeout for file uploads in seconds (default: 1800 seconds = 30 minutes)

# Character used for separating log blocks
separator_char: "*"

# Define a standard length for the calculation (must be an integer)
default_message_padding: 4

rh_case_update_use_proxy: "{{ use_proxy | default(false) }}"
rh_case_update_http_proxy: "{{ http_proxy | default('') }}"
...
