---
# Defines the API endpoints to query for each component type

aap_api_endpoints:
  gateway:
    - "/api/gateway/v1/ping/"
    - "/api/gateway/v1/status/"
    - "/api/gateway/v1/authenticators/"
    - "/api/gateway/v1/legacy_auth/"
    - "/api/gateway/v1/me/"
    - "/api/gateway/v1/service_clusters/"
    - "/api/gateway/v1/service_nodes/"
    - "/api/gateway/v1/session/"
    - "/api/gateway/v1/ui_auth/"
    - "/api/gateway/v1/users/"
  controller:
    - "/api/controller/v2/config/"
    - "/api/controller/v2/credential_types/"
    - "/api/controller/v2/execution_environments/"
    - "/api/controller/v2/instances/"
    - "/api/controller/v2/job_templates/"
    - "/api/controller/v2/jobs/"
    - "/api/controller/v2/ping/"
    - "/api/controller/v2/project_updates/"
    - "/api/controller/v2/projects/"
    - "/api/controller/v2/service-index/metadata/"
    - "/api/controller/v2/settings/all/"
    - "/api/controller/v2/settings/authentication/"
    - "/api/controller/v2/settings/jobs/"
    - "/api/controller/v2/settings/ldap/"
    - "/api/controller/v2/settings/oidc/"
    - "/api/controller/v2/settings/saml/"
    - "/api/controller/v2/settings/system/"
    - "/api/controller/v2/status/"
    - "/api/controller/v2/tokens/"
    - "/api/controller/v2/unified_jobs/"
    - "/api/controller/v2/workflow_job_templates/"
    - "/api/controller/v2/workflow_jobs/"
  hub:
    - "/pulp/api/v3/status/"
    - "/pulp/api/v3/tasks/"
    - "/pulp/api/v3/repositories/container/container/"
    - "/pulp/api/v3/repositories/container/container-push/"
  eda: []

aap_api_legacy_endpoints:
  controller:
    - "/api/v2/ping/"
    - "/api/v2/instances/"
    - "/api/v2/settings/all/"
    - "/api/v2/config/"
    - "/api/v2/credential_types/"
    - "/api/v2/execution_environments/"
    - "/api/v2/job_templates/"
    - "/api/v2/jobs/"
    - "/api/v2/project_updates/"
    - "/api/v2/projects/"
    - "/api/v2/settings/authentication/"
    - "/api/v2/settings/jobs/"
    - "/api/v2/settings/ldap/"
    - "/api/v2/settings/oidc/"
    - "/api/v2/settings/saml/"
    - "/api/v2/settings/system/"
    - "/api/v2/status/"
    - "/api/v2/tokens/"
    - "/api/v2/unified_jobs/"
    - "/api/v2/workflow_job_templates/"
    - "/api/v2/workflow_jobs/"
  hub:
    - "/pulp/api/v3/status/"
    - "/pulp/api/v3/tasks/"
    - "/pulp/api/v3/repositories/container/container/"
    - "/pulp/api/v3/repositories/container/container-push/"
  eda: []
...
