---
galaxy_info:
  author: Lenny Shirley
  description: Uploads files or adds comments to a Red Hat Support Case
  company: Red Hat
  issue_tracker_url: https://github.com/redhat-cop/infra.support_assist/issues
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  galaxy_tags: []
dependencies:
  - role: rh_token_refresh
...
