# Central dictionary containing all environment-specific settings
---
rh_env_config:
  prod:
    rh_base_url: "https://access.redhat.com"
    rh_token_refresh_api_base_url: "https://api.access.redhat.com"
    rh_token_refresh_api_token_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
    rh_use_proxy: false
    rh_http_proxy: ""
  qa:
    rh_base_url: "https://access.qa.redhat.com"
    rh_token_refresh_api_base_url: "https://api.access.qa.redhat.com"
    rh_token_refresh_api_token_url: "https://sso.qa.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
    rh_use_proxy: true
    rh_http_proxy: "http://squid.corp.redhat.com:3128"
  staging:
    rh_base_url: "https://access.stage.redhat.com"
    rh_token_refresh_api_base_url: "https://access.stage.redhat.com"
    rh_token_refresh_api_token_url: "https://sso.stage.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
    rh_use_proxy: true
    rh_http_proxy: "http://squid.corp.redhat.com:3128"
...
