---
galaxy_info:
  author: "Lenny Shirley, Diego Felipe Mateus"
  description: "Unified role for creating and updating Red Hat Support Cases via API"
  company: Red Hat
  issue_tracker_url: https://github.com/redhat-cop/infra.support_assist/issues
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  galaxy_tags: []
dependencies:
  - role: rh_token_refresh
...
