---
- name: Converge
  hosts: all
  tasks:
    - name: "Include rh_token_refresh"
      ansible.builtin.include_role:
        name: "rh_token_refresh"
      vars:
        offline_token: "test_token_placeholder"
      # Note: This will fail without valid Red Hat API token, but tests role structure
...
