---
- name: display_case_update_summary_trigger
  ansible.builtin.debug:
    msg: "FINAL EXECUTION SUMMARY:\n{{ summary_data | to_nice_yaml }}"
  vars:
    summary_data:
      SUMMARY_STATUS: "Red Hat Support Case {{ case_id }} Created and Updated Successfully."
      
      CASE_IDENTIFIERS:
        Account_Name: "{{ account_name }}"
        Account_Ref: "{{ accountNumberRef }}"
        Case_ID: "{{ case_id }}"
        Case_URL: "{{ rh_base_url }}/support/cases/#/case/{{ case_id }}"
        
      PROBLEM_DETAILS:
        Product: "{{ case_product }}"
        Version: "{{ case_product_version }}"
        Severity: "{{ case_severity }}"
        Issue_Type: "{{ case_type }}"
        Summary_Text: "{{ case_summary | trim }}"
        
      ACTION_REQUIRED:
        Description: "{{ case_description | default(case_summary) }}"
        Review_URL: "{{ rh_base_url }}/support/cases/#/case/{{ case_id }}"

  listen: "display_case_update_summary_trigger"
...
