---
- name: Install
  ansible.builtin.include_tasks: install.yml

- name: Block
  block:
    - name: Generate
      ansible.builtin.include_tasks: generate.yml

    - name: Fetch
      ansible.builtin.include_tasks: fetch.yml

  always:
    - name: Cleanup
      when: sos_report_cleanup | bool
      ansible.builtin.include_tasks: cleanup.yml
...
