---
# Based on ansible-lint config
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'

ignore: |
  .travis.yml
  .ansible-lint
  .yamllint
  .github
  .tox/
  .cache/
  collections/
  docs/
  roles_bak/

# https://yamllint.readthedocs.io/en/stable/rules.html
rules:
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.braces
  ### e.g: {{ VARIABLE }}
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 1
    level: error
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.brackets
  ### e.g: [ 1, 2, abc ]
  brackets:
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 1
    level: error
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.colons
  #### e.g: object:
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
    level: error
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.commas
  ### e.g: [10, 20, 30, 40]
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
    level: error
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 2
  comments-indentation: disable
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_start
  document-start:
    present: true
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_end
  document-end:
    present: true
  empty-lines:
    max: 2
    level: error
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.hyphens
  hyphens:
    max-spaces-after: 1
    level: error
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.indentation
  indentation:
    spaces: 2
    indent-sequences: whatever
    check-multi-line-strings: false
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.key_duplicates
  key-duplicates: enable
  line-length:
    max: 110
    level: warning
  new-line-at-end-of-file: disable
  new-lines: disable
  # https://yamllint.readthedocs.io/en/stable/rules.html#:~:text=city-code%3A%200o10-,quoted-strings,-Use%20this%20rule
  quoted-strings: disable
  trailing-spaces: disable
  truthy: disable
...
